#!/usr/bin/env python3
"""Project agents/roles/ (authoring single source) into per-harness registries.

三源投影（AIR-91 S2）：agents/roles/*.md＝authoring 單一源（frontmatter
白名單 name/description/tools/background，零 model／harness 字樣）；
agents/presets.toml＝deployment 單一源（registry slug→harness membership／
read-write／sandbox／background 鏡像／default binding——FK 到 catalog）；
skills/model-routing/catalog.toml＝model 供給事實單一源（binding 本體——
wire token／token kind／effort encoding）。本檔把三者投影成 agents/zcode/
與 agents/claude/ 生成物（ownership marker 標記）——projection-only：不讀
memory、不 probe availability、不執行 runtime resolver（正式 resolver＝
model-routing skill 的 instruction protocol）。

安全模型：compute-then-apply——check/map 在任何 mkdir/write/unlink 前
return（零寫入）；sync 才進 mutation boundary。寫入走 temp file＋
os.replace（原子——撕裂態不留 marker 半損殘骸）。stale cleanup 只刪
marker-owned；unmarked 同名檔一律 fail（唯一例外＝一次性 --adopt-legacy
對固定 legacy 路徑、expected 減 marker 後逐檔 exact bytes 相等者——
一次性模式，首次遷移完成後不再使用）。
"""

import argparse
import os
import re
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path

OWNERSHIP_MARKER = "<!-- generated by scripts/sync_agents.py; do not edit -->"

# CC 端 CR MCP 白名單是 ZCode-only 接線（known divergence：claude 拷貝剝除）
CR_MCP_PREFIX = "mcp__plugin_code-reality_code-reality__"

# 首次遷移的 legacy unmarked 輸出（AIR-28 前手動 cp 拓撲殘留）；
# --adopt-legacy 僅收編這些路徑，完成後不再使用
LEGACY_REVIEWER_OUTPUTS = {
    "agents/zcode/code-reviewer.md",
    "agents/zcode/code-reviewer-primed.md",
    "agents/claude/code-reviewer.md",
    "agents/claude/code-reviewer-primed.md",
}


def load_role_specs(repo: Path) -> dict[str, str]:
    role_dir = repo / "agents" / "roles"
    return {
        path.stem: path.read_text(encoding="utf-8")
        for path in sorted(role_dir.glob("*.md"))
    }


# ------------------------------------------------------------------
# AIR-91 S1：model supply catalog（loader／validator）。
# catalog 只承載供給事實（ModelIdentity／DispatchBinding／qualification）；
# Role／work_unit／authority／registry slug／preset 與 volatile 欄位（quota／
# reset／account／available-now）由 loader fail-loud 拒絕——demand 屬 workflow、
# deployment 屬 presets、volatile 屬 AvailabilitySnapshot 輸入。
# 正式 resolver 是 model-routing skill 的 instruction protocol，不在此實作。
# （AIR-91 S2 legacy tier→pin dict／skill 表 parser／check_parity 已於等價
# gate 通過後移除——對照組凍結在 tests LEGACY_* golden。）
# ------------------------------------------------------------------

CATALOG_SOURCE = Path("skills/model-routing/catalog.toml")

_TOKEN_KINDS = frozenset({"provider_native", "harness_alias", "carrier_slug"})
_EFFORT_ENCODINGS = frozenset({"field", "param", "slug_fixed", "unsupported"})
_TRANSPORT_CAPS = frozenset({"image_transport"})
_CAPABILITY_NAMES = frozenset({"native_vision"})
_QUAL_STATUSES = frozenset({"qualified", "conditional", "unqualified"})
_EVIDENCE_SOURCES = frozenset(
    {"user_observed", "repo_observed", "official_documentation", "pending_first_use"}
)
# volatile／demand／deployment 欄位禁令（exact key 遞迴掃描）
_FORBIDDEN_CATALOG_KEYS = frozenset(
    {
        "role",
        "roles",
        "work_unit",
        "authority",
        "registry_slug",
        "preset",
        "quota",
        "reset",
        "account",
        "available",
        "available_now",
        "availability",
        "entitlement",
    }
)
_PROVIDER_NATIVE_TOKEN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.\-]*$")
_CARRIER_SLUG_TOKEN_RE = re.compile(r"^[a-z0-9][a-z0-9\-]*/[a-z0-9][a-z0-9\-]*$")
# effort 序（跨家族詞彙→語義檔位；語義源＝model-routing skill「effort 家族對譯表」）
_EFFORT_ORDINAL = {
    "none": 0,
    "minimal": 1,
    "low": 2,
    "medium": 3,
    "high": 4,
    "xhigh": 5,
    "ultra": 5,
    "max": 5,
}


@dataclass(frozen=True)
class ModelCapability:
    name: str
    evidence: str


@dataclass(frozen=True)
class ModelIdentity:
    id: str
    label: str
    capabilities: tuple[ModelCapability, ...]


@dataclass(frozen=True)
class DispatchBinding:
    id: str
    model_identity: str
    carrier: str
    surface: str
    token: str
    token_kind: str
    family: str
    effort_encoding: str
    effort_values: tuple[str, ...]
    fixed_effort: str | None
    transport: tuple[str, ...]


@dataclass(frozen=True)
class QualificationRecord:
    workload: str
    model_identity: str
    status: str
    evidence_source: str
    binding_scope: tuple[str, ...]
    minimum_effective_effort: str | None


@dataclass(frozen=True)
class ModelCatalog:
    workloads: frozenset[str]
    harness_alias_tokens: frozenset[str]
    families: frozenset[str]
    identities: dict[str, ModelIdentity]
    bindings: dict[str, DispatchBinding]
    qualifications: tuple[QualificationRecord, ...]


def _catalog_keys_ok(table: dict, allowed: frozenset[str], where: str) -> None:
    illegal = set(table) - allowed
    assert not illegal, (
        f"catalog: {where}: 鍵 {sorted(illegal)} 超出白名單 {sorted(allowed)}"
    )


def _catalog_required(table: dict, keys: tuple[str, ...], where: str) -> None:
    for key in keys:
        assert key in table, f"catalog: {where}: 缺必要鍵 {key!r}"


def _reject_forbidden_keys(node: object, path: str, forbidden: frozenset[str]) -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            assert key not in forbidden, (
                f"{path.split('.')[0]}: 禁止欄位 {key!r}（volatile／demand state"
                f" 不住此源——{path}.{key}）"
            )
            _reject_forbidden_keys(value, f"{path}.{key}", forbidden)
    elif isinstance(node, list):
        for item in node:
            _reject_forbidden_keys(item, path, forbidden)


def parse_catalog(text: str) -> ModelCatalog:
    """解析＋驗證 catalog（schema／enum／token 混型／FK／唯一性／volatile 欄位）。

    任何違規＝AssertionError（caller fail loud）；通過＝可供機械查詢的
    ModelCatalog（identity／binding／qualification 供給事實）。
    """
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise AssertionError(f"catalog: TOML 語法錯誤——{exc}") from exc
    _reject_forbidden_keys(data, "catalog", _FORBIDDEN_CATALOG_KEYS)
    _catalog_keys_ok(
        data,
        frozenset(
            {
                "schema_version",
                "allow_lists",
                "model_identity",
                "dispatch_binding",
                "qualification",
            }
        ),
        "頂層",
    )
    version = data.get("schema_version")
    assert version == 1, f"catalog: schema_version {version!r}（預期 1）"
    allow = data.get("allow_lists", {})
    _catalog_keys_ok(
        allow,
        frozenset({"workloads", "harness_alias_tokens", "families"}),
        "allow_lists",
    )
    for list_key in ("workloads", "harness_alias_tokens", "families"):
        values = allow.get(list_key)
        assert (
            isinstance(values, list)
            and values
            and all(isinstance(v, str) and v for v in values)
        ), f"catalog: allow_lists.{list_key} 需非空字串清單"
        assert len(values) == len(set(values)), (
            f"catalog: allow_lists.{list_key} 有重複值"
        )
    workloads = frozenset(allow["workloads"])
    alias_tokens = frozenset(allow["harness_alias_tokens"])
    families = frozenset(allow["families"])

    # --- model_identity ---
    identities: dict[str, ModelIdentity] = {}
    identity_rows = data.get("model_identity", [])
    for row in identity_rows:
        _catalog_keys_ok(
            row, frozenset({"id", "label", "capability"}), "model_identity"
        )
        _catalog_required(row, ("id",), "model_identity")
        mid = row["id"]
        assert mid not in identities, f"catalog: duplicate model_identity id {mid!r}"
        capabilities: list[ModelCapability] = []
        cap_names: set[str] = set()
        for cap in row.get("capability", []):
            _catalog_keys_ok(cap, frozenset({"name", "evidence"}), "capability")
            _catalog_required(cap, ("name", "evidence"), "capability")
            assert cap["name"] in _CAPABILITY_NAMES, (
                f"catalog: capability name {cap['name']!r} 不在詞彙"
                f"（合法：{sorted(_CAPABILITY_NAMES)}）"
            )
            assert cap["evidence"] in _EVIDENCE_SOURCES, (
                f"catalog: capability evidence {cap['evidence']!r} 不在詞彙"
                f"（合法：{sorted(_EVIDENCE_SOURCES)}）"
            )
            assert cap["name"] not in cap_names, (
                f"catalog: model_identity {mid!r} capability {cap['name']!r} 重複"
            )
            cap_names.add(cap["name"])
            capabilities.append(ModelCapability(cap["name"], cap["evidence"]))
        identities[mid] = ModelIdentity(mid, row.get("label", mid), tuple(capabilities))

    # --- dispatch_binding ---
    bindings: dict[str, DispatchBinding] = {}
    token_scopes: set[tuple[str, str, str, str]] = set()
    for row in data.get("dispatch_binding", []):
        _catalog_keys_ok(
            row,
            frozenset(
                {
                    "id",
                    "model_identity",
                    "carrier",
                    "surface",
                    "token",
                    "token_kind",
                    "family",
                    "effort_encoding",
                    "effort_values",
                    "fixed_effort",
                    "transport",
                }
            ),
            "dispatch_binding",
        )
        _catalog_required(
            row,
            (
                "id",
                "model_identity",
                "carrier",
                "surface",
                "token",
                "token_kind",
                "family",
                "effort_encoding",
            ),
            "dispatch_binding",
        )
        bid = row["id"]
        assert bid not in bindings, f"catalog: duplicate dispatch_binding id {bid!r}"
        mid = row["model_identity"]
        assert mid in identities, (
            f"catalog: binding {bid!r} model_identity {mid!r} 未定義"
        )
        kind = row["token_kind"]
        assert kind in _TOKEN_KINDS, (
            f"catalog: unknown token_kind {kind!r}（合法：{sorted(_TOKEN_KINDS)}）"
        )
        family = row["family"]
        assert family in families, (
            f"catalog: binding {bid!r}: unknown family {family!r}"
            f"（合法：{sorted(families)}——allow_lists.families 閉集）"
        )
        token = row["token"]
        if kind == "provider_native":
            assert _PROVIDER_NATIVE_TOKEN_RE.match(token), (
                f"catalog: binding {bid!r}: provider_native token {token!r} 含非法"
                "字元或 carrier slug 形態——native/alias/slug 禁混型"
            )
        elif kind == "harness_alias":
            assert token in alias_tokens, (
                f"catalog: binding {bid!r}: harness_alias token {token!r} 不在"
                " allow_lists.harness_alias_tokens——native/alias/slug 禁混型"
            )
        else:
            assert _CARRIER_SLUG_TOKEN_RE.match(token), (
                f"catalog: binding {bid!r}: carrier_slug token {token!r} 非 carrier"
                " 限定形態（須含 '/'，如 chatgpt-web/high）——native/alias/slug 禁混型"
            )
        scope = (row["carrier"], row["surface"], kind, token)
        assert scope not in token_scopes, (
            f"catalog: duplicate token scope (carrier={row['carrier']!r}, "
            f"surface={row['surface']!r}, token_kind={kind!r}, token={token!r})"
            "——同 token 在同 carrier/surface 只能有一個 binding"
        )
        token_scopes.add(scope)
        encoding = row["effort_encoding"]
        assert encoding in _EFFORT_ENCODINGS, (
            f"catalog: binding {bid!r}: unknown effort_encoding {encoding!r}"
            f"（合法：{sorted(_EFFORT_ENCODINGS)}）"
        )
        values = tuple(row.get("effort_values", []))
        fixed = row.get("fixed_effort")
        if encoding in {"field", "param"}:
            assert values and fixed is None, (
                f"catalog: binding {bid!r} effort_encoding={encoding!r} 形態不符"
                "（slug_fixed 需 fixed_effort；field/param 需 effort_values；"
                "unsupported 兩者皆禁）"
            )
        elif encoding == "slug_fixed":
            assert fixed is not None and not values, (
                f"catalog: binding {bid!r} effort_encoding={encoding!r} 形態不符"
            )
        else:
            assert fixed is None and not values, (
                f"catalog: binding {bid!r} effort_encoding={encoding!r} 形態不符"
            )
        for value in (*values, fixed):
            if value is not None:
                assert value in _EFFORT_ORDINAL, (
                    f"catalog: binding {bid!r}: effort token {value!r} 不在"
                    f" _EFFORT_ORDINAL 跨家族詞彙（{sorted(_EFFORT_ORDINAL)}）"
                )
        transport = tuple(row.get("transport", []))
        assert set(transport) <= _TRANSPORT_CAPS, (
            f"catalog: binding {bid!r} transport {sorted(set(transport) - _TRANSPORT_CAPS)}"
            f" 不在詞彙（合法：{sorted(_TRANSPORT_CAPS)}）"
        )
        bindings[bid] = DispatchBinding(
            bid,
            mid,
            row["carrier"],
            row["surface"],
            token,
            kind,
            family,
            encoding,
            values,
            fixed,
            transport,
        )

    # --- qualification ---
    records: list[QualificationRecord] = []
    scopes_by_key: dict[tuple[str, str], list[tuple[str, ...]]] = {}
    for row in data.get("qualification", []):
        _catalog_keys_ok(
            row,
            frozenset(
                {
                    "workload",
                    "model_identity",
                    "status",
                    "evidence_source",
                    "binding_scope",
                    "minimum_effective_effort",
                }
            ),
            "qualification",
        )
        _catalog_required(
            row,
            (
                "workload",
                "model_identity",
                "status",
                "evidence_source",
                "binding_scope",
            ),
            "qualification",
        )
        workload = row["workload"]
        assert workload in workloads, (
            f"catalog: workload {workload!r} 不在 allow_lists.workloads"
            f"（合法：{sorted(workloads)}）"
        )
        mid = row["model_identity"]
        assert mid in identities, (
            f"catalog: qualification({workload},{mid}) model_identity 未定義"
        )
        status = row["status"]
        assert status in _QUAL_STATUSES, (
            f"catalog: qualification status {status!r} 不在詞彙"
            f"（合法：{sorted(_QUAL_STATUSES)}）；availability 禁入 status/evidence 欄"
        )
        evidence = row["evidence_source"]
        assert evidence in _EVIDENCE_SOURCES, (
            f"catalog: evidence_source {evidence!r} 不在詞彙"
            f"（合法：{sorted(_EVIDENCE_SOURCES)}）；availability 禁入 status/evidence 欄"
        )
        scope = tuple(row["binding_scope"])
        assert scope, "catalog: qualification binding_scope 不可為空"
        for scoped_id in scope:
            if scoped_id == "*":
                continue
            assert scoped_id in bindings, (
                f"catalog: qualification({workload},{mid}) scope 引用不存在的"
                f" binding {scoped_id!r}"
            )
            owner = bindings[scoped_id].model_identity
            assert owner == mid, (
                f"catalog: qualification({workload},{mid}) scope binding"
                f" {scoped_id!r} 屬 model_identity {owner!r} 非 {mid!r}"
            )
        key = (workload, mid)
        for existing in scopes_by_key.get(key, []):
            assert not ("*" in existing or "*" in scope or existing == scope), (
                f"catalog: qualification({workload},{mid}) scope 重疊——同"
                " (workload, model_identity) 的 scope 禁互疊（'*' 含一切）"
            )
        scopes_by_key.setdefault(key, []).append(scope)
        minimum = row.get("minimum_effective_effort")
        if minimum is not None:
            assert minimum in _EFFORT_ORDINAL, (
                f"catalog: minimum_effective_effort {minimum!r} 不在跨家族詞彙"
                f"（{sorted(_EFFORT_ORDINAL)}）"
            )
            if status == "qualified":
                scoped_bindings = (
                    [b for b in bindings.values() if b.model_identity == mid]
                    if "*" in scope
                    else [bindings[sid] for sid in scope]
                )
                assert any(
                    b.effort_encoding != "unsupported" for b in scoped_bindings
                ), (
                    f"catalog: qualification({workload},{mid}) status=qualified 帶"
                    " minimum_effective_effort，但 scope 內無 binding 可確認"
                    " effective effort——此形態只能 conditional（不滿足 decision"
                    " hard gate）"
                )
        records.append(
            QualificationRecord(workload, mid, status, evidence, scope, minimum)
        )

    return ModelCatalog(
        workloads, alias_tokens, families, identities, bindings, tuple(records)
    )


def load_catalog(repo: Path) -> ModelCatalog:
    """讀取 repo 的 catalog（缺檔＝FileNotFoundError——caller 先驗存在性）。"""
    return parse_catalog((repo / CATALOG_SOURCE).read_text(encoding="utf-8"))


# --- 供給面機械查詢（無 demand 知識；resolver 語義歸 model-routing skill）---


def effective_effort(
    binding: DispatchBinding, requested_effort: str | None
) -> str | None:
    """binding 對 effective effort 的確認結果（None＝無法確認，fail-closed）。"""
    if binding.effort_encoding == "slug_fixed":
        return binding.fixed_effort
    if binding.effort_encoding == "unsupported":
        return None
    if requested_effort is not None and requested_effort in binding.effort_values:
        return requested_effort
    return None


def qualification_for(
    catalog: ModelCatalog, workload: str, binding: DispatchBinding
) -> QualificationRecord | None:
    """適用於 (workload, binding) 的記錄（scope 命中；載入時已保證至多一筆）。"""
    for rec in catalog.qualifications:
        if (
            rec.workload == workload
            and rec.model_identity == binding.model_identity
            and ("*" in rec.binding_scope or binding.id in rec.binding_scope)
        ):
            return rec
    return None


def direct_visual_eligible(catalog: ModelCatalog, binding: DispatchBinding) -> bool:
    """direct visual eligibility＝ModelIdentity.native_vision ∩ binding.image_transport。"""
    identity = catalog.identities.get(binding.model_identity)
    native = identity is not None and any(
        cap.name == "native_vision" for cap in identity.capabilities
    )
    return native and "image_transport" in binding.transport


def passes_decision_hard_gate(
    catalog: ModelCatalog,
    workload: str,
    binding: DispatchBinding,
    requested_effort: str | None,
) -> bool:
    """decision hard gate（機械層）：status=qualified 且（如有 minimum）effective
    effort 可確認且達標。conditional／無記錄／effort 無法確認——皆不過 gate；
    effort 不能把未 qualification 的 candidate 補成 decision-qualified。
    """
    rec = qualification_for(catalog, workload, binding)
    if rec is None or rec.status != "qualified":
        return False
    if rec.minimum_effective_effort is None:
        return True
    effort = effective_effort(binding, requested_effort)
    return effort is not None and (
        _EFFORT_ORDINAL[effort] >= _EFFORT_ORDINAL[rec.minimum_effective_effort]
    )


# ------------------------------------------------------------------
# AIR-91 S2：deployment presets（loader／validator／binding 解析）。
# presets 只承載 registry slug 的 harness 部署設定（membership／read-write／
# sandbox／background 鏡像／default binding FK）；Role／authority／
# qualification／workload／judgment floor（demand）與 volatile state 由 loader
# fail-loud 拒絕。requirement 欄＝legacy --map 四欄相容 token，非路由依據。
# 本段與 catalog 一起構成 registry projection 的唯一機械源。
# ------------------------------------------------------------------

PRESET_SOURCE = Path("agents/presets.toml")

_PRESET_HARNESS_CARRIERS = {"zcode": "zcode", "claude": "claude-code"}
_PRESET_READ_WRITE = frozenset({"read-only", "read-write"})
_PRESET_SANDBOX = frozenset({"default"})
# demand／volatile 欄位禁令（exact key 遞迴掃描；requirement＝相容 token 不禁）
_FORBIDDEN_PRESET_KEYS = frozenset(
    {
        "role",
        "roles",
        "authority",
        "qualification",
        "qualifications",
        "workload",
        "work_unit",
        "judgment",
        "judgment_floor",
        "available",
        "available_now",
        "availability",
        "entitlement",
        "quota",
        "reset",
        "account",
    }
)


@dataclass(frozen=True)
class Preset:
    slug: str
    requirement: str
    harness: tuple[str, ...]
    read_write: str
    sandbox: str
    background: bool
    # harness -> (binding ref, deployment effort | None)
    default_binding: dict[str, tuple[str, str | None]]


def parse_presets(text: str) -> dict[str, Preset]:
    """解析＋驗證 presets（schema／enum／forbidden 欄位／membership 一致性）。

    任何違規＝AssertionError（caller fail loud）；FK 到 catalog 的部分在
    resolve_deployment 驗（parse 無 catalog 知識）。
    """
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise AssertionError(f"presets: TOML 語法錯誤——{exc}") from exc
    _reject_forbidden_keys(data, "presets", _FORBIDDEN_PRESET_KEYS)
    _catalog_keys_ok(
        data, frozenset({"schema_version", "allow_lists", "preset"}), "presets 頂層"
    )
    version = data.get("schema_version")
    assert version == 1, f"presets: schema_version {version!r}（預期 1）"
    allow = data.get("allow_lists", {})
    _catalog_keys_ok(
        allow, frozenset({"harnesses", "requirements"}), "presets allow_lists"
    )
    for list_key in ("harnesses", "requirements"):
        values = allow.get(list_key)
        assert (
            isinstance(values, list)
            and values
            and all(isinstance(v, str) and v for v in values)
        ), f"presets: allow_lists.{list_key} 需非空字串清單"
        assert len(values) == len(set(values)), (
            f"presets: allow_lists.{list_key} 有重複值"
        )
    harness_vocab = frozenset(allow["harnesses"])
    requirement_vocab = frozenset(allow["requirements"])

    presets: dict[str, Preset] = {}
    for row in data.get("preset", []):
        _catalog_keys_ok(
            row,
            frozenset(
                {
                    "slug",
                    "requirement",
                    "harness",
                    "read_write",
                    "sandbox",
                    "background",
                    "default_binding",
                }
            ),
            "preset",
        )
        _catalog_required(
            row,
            ("slug", "requirement", "harness", "read_write", "sandbox", "background"),
            "preset",
        )
        slug = row["slug"]
        assert isinstance(slug, str) and slug, "presets: slug 需非空字串"
        assert slug not in presets, f"presets: duplicate slug {slug!r}"
        requirement = row["requirement"]
        assert requirement in requirement_vocab, (
            f"presets: preset {slug!r} unknown requirement {requirement!r}"
            f"（合法：{sorted(requirement_vocab)}）——legacy --map 相容 token"
        )
        harness = row["harness"]
        assert isinstance(harness, list) and harness, (
            f"presets: preset {slug!r} harness 需非空清單"
        )
        assert len(harness) == len(set(harness)), (
            f"presets: preset {slug!r} harness 有重複值"
        )
        for member in harness:
            assert member in harness_vocab, (
                f"presets: preset {slug!r} harness {member!r} 不在"
                f" allow_lists.harnesses（合法：{sorted(harness_vocab)}）"
            )
        read_write = row["read_write"]
        assert read_write in _PRESET_READ_WRITE, (
            f"presets: preset {slug!r} read_write {read_write!r} 不在詞彙"
            f"（合法：{sorted(_PRESET_READ_WRITE)}）"
        )
        sandbox = row["sandbox"]
        assert sandbox in _PRESET_SANDBOX, (
            f"presets: preset {slug!r} sandbox {sandbox!r} 不在詞彙"
            f"（合法：{sorted(_PRESET_SANDBOX)}）"
        )
        background = row["background"]
        assert isinstance(background, bool), (
            f"presets: preset {slug!r} background 需 bool"
        )
        default_binding = row.get("default_binding", {})
        assert isinstance(default_binding, dict), (
            f"presets: preset {slug!r} default_binding 需 table"
        )
        refs: dict[str, tuple[str, str | None]] = {}
        for member, entry in default_binding.items():
            assert member in harness, (
                f"presets: preset {slug!r} default_binding 宣告 {member!r} 但"
                f" harness membership 未含——membership 與 binding 需一致"
            )
            assert isinstance(entry, dict), (
                f"presets: preset {slug!r} default_binding.{member} 需 table"
            )
            _catalog_keys_ok(
                entry, frozenset({"ref", "effort"}), f"preset {slug} {member} binding"
            )
            _catalog_required(entry, ("ref",), f"preset {slug} {member} binding")
            ref = entry["ref"]
            assert isinstance(ref, str) and ref, (
                f"presets: preset {slug!r} default_binding.{member} ref 需非空字串"
            )
            effort = entry.get("effort")
            if effort is not None:
                assert effort in _EFFORT_ORDINAL, (
                    f"presets: preset {slug!r} effort token {effort!r} 不在跨家族"
                    f"詞彙（{sorted(_EFFORT_ORDINAL)}）"
                )
            refs[member] = (ref, effort)
        presets[slug] = Preset(
            slug, requirement, tuple(harness), read_write, sandbox, background, refs
        )
    assert presets, "presets: preset 清單不可為空"
    return presets


def load_presets(repo: Path) -> dict[str, Preset]:
    """讀取 repo 的 presets（缺檔＝FileNotFoundError——source of record 必在）。"""
    return parse_presets((repo / PRESET_SOURCE).read_text(encoding="utf-8"))


def resolve_deployment(
    catalog: ModelCatalog, presets: dict[str, Preset]
) -> dict[str, dict[str, tuple[DispatchBinding | None, str | None]]]:
    """preset default binding → (binding, deployment effort)；驗 FK／carrier／effort 形態。

    無 default binding 的 harness＝inherit ((None, None)——registry 檔無 model
    欄位，spawn-time 決定)。registry 投影只收 effort_encoding=field（zcode
    thoughtLevel 欄位）／param（CC spawn-time enum——frontmatter 僅 model）；
    slug_fixed／unsupported 是 bridge carrier 形態，非 registry 部署面。
    """
    resolved: dict[str, dict[str, tuple[DispatchBinding | None, str | None]]] = {}
    for slug, preset in sorted(presets.items()):
        per: dict[str, tuple[DispatchBinding | None, str | None]] = {}
        for member in preset.harness:
            entry = preset.default_binding.get(member)
            if entry is None:
                per[member] = (None, None)
                continue
            ref, effort = entry
            binding = catalog.bindings.get(ref)
            assert binding is not None, (
                f"presets: preset {slug!r} default_binding[{member}] 引用不存在的"
                f" binding {ref!r}"
            )
            carrier = _PRESET_HARNESS_CARRIERS.get(member)
            assert carrier is not None, (
                f"presets: harness {member!r} 無 registry carrier 對應"
                f"（已知：{sorted(_PRESET_HARNESS_CARRIERS)}）"
            )
            assert binding.carrier == carrier, (
                f"presets: preset {slug!r} default_binding[{member}]＝{ref!r} "
                f"carrier {binding.carrier!r} 與 harness {member!r}（{carrier!r}）"
                " 不相容"
            )
            if binding.effort_encoding == "field":
                assert effort is not None, (
                    f"presets: preset {slug!r} binding {ref!r} effort_encoding="
                    "field 需部署 effort（thoughtLevel）"
                )
                assert effort in binding.effort_values, (
                    f"presets: preset {slug!r} 部署 effort {effort!r} 不在 binding"
                    f" {ref!r} effort_values {list(binding.effort_values)}"
                    "——capability mismatch"
                )
            elif binding.effort_encoding == "param":
                assert effort is None, (
                    f"presets: preset {slug!r} binding {ref!r} effort_encoding=param"
                    "（spawn-time enum）——registry frontmatter 不帶 effort"
                )
            else:
                raise AssertionError(
                    f"presets: binding {ref!r} effort_encoding="
                    f"{binding.effort_encoding!r} 非 registry 部署形態"
                    "（slug_fixed／unsupported＝bridge carrier 面）"
                )
            per[member] = (binding, effort)
        resolved[slug] = per
    return resolved


_FRONTMATTER_ALLOWLIST = {"name", "description", "tools", "background"}


def split_frontmatter(role_name: str, role_body: str) -> tuple[str, str]:
    """前置驗證＋切分 frontmatter/body（BOM／缺 frontmatter／空 frontmatter 分別報）。"""
    if role_body.startswith("\ufeff"):
        raise AssertionError(f"{role_name}: frontmatter 前有 BOM——去掉後重存")
    if not role_body.startswith("---\n"):
        raise AssertionError(f"{role_name}: 缺 frontmatter（首行必須是 ---）")
    if role_body.startswith("---\n---\n"):
        raise AssertionError(
            f"{role_name}: frontmatter 為空（至少需 name/description）"
        )
    frontmatter, separator, body = role_body[4:].partition("\n---\n")
    if not separator:
        raise AssertionError(f"{role_name}: frontmatter 未閉合（缺 --- 結尾欄）")
    if not frontmatter.strip():
        raise AssertionError(
            f"{role_name}: frontmatter 為空（至少需 name/description）"
        )
    keys = {
        line.split(":", 1)[0].strip()
        for line in frontmatter.splitlines()
        if line.strip()
    }
    illegal = keys - _FRONTMATTER_ALLOWLIST
    if illegal:
        raise AssertionError(
            f"{role_name}: frontmatter 鍵 {sorted(illegal)} 超出白名單 "
            f"{sorted(_FRONTMATTER_ALLOWLIST)}（model/thoughtLevel 屬投影層——pins 由 sync 生成）"
        )
    return frontmatter, body


def project_tools(frontmatter: str, target: str) -> str:
    lines: list[str] = []
    for line in frontmatter.splitlines():
        if target == "claude" and line.startswith("tools:"):
            key, raw_tools = line.split(":", maxsplit=1)
            tools = [tool.strip() for tool in raw_tools.split(",")]
            tools = [
                tool for tool in tools if tool and not tool.startswith(CR_MCP_PREFIX)
            ]
            if not tools:
                raise AssertionError(
                    "claude 投影後 tools 全空（源 tools 只有 CR MCP 全名？）"
                    "—— CC 端語義未定義，先修 roles/ 源補非 CR tools"
                )
            line = f"{key}: {', '.join(tools)}"
        lines.append(line)
    return "\n".join(lines)


def render_registry(
    role_name: str,
    role_body: str,
    target: str,
    binding: DispatchBinding | None,
    effort: str | None,
) -> str:
    """投影 role 定義＋deployment binding（binding=None＝inherit——無 model 欄位）。

    zcode：effort_encoding=field → model＋thoughtLevel；claude：param → 僅
    model（CC effort＝spawn-time enum 非 frontmatter）。tools 的 CR MCP 剝除
    分歧由 project_tools 承載（不變）。
    """
    frontmatter, body = split_frontmatter(role_name, role_body)
    frontmatter = project_tools(frontmatter, target)
    target_fields = ""
    if binding is not None:
        if target == "zcode":
            target_fields = f"\nmodel: {binding.token}\nthoughtLevel: {effort}"
        else:
            target_fields = f"\nmodel: {binding.token}"
    return f"---\n{frontmatter}{target_fields}\n---\n{OWNERSHIP_MARKER}\n{body}"


def is_owned(file_text: str) -> bool:
    if not file_text.startswith("---\n"):
        return False
    _, separator, body = file_text[4:].partition("\n---\n")
    return bool(separator) and body.startswith(f"{OWNERSHIP_MARKER}\n")


def without_marker(file_text: str) -> str:
    return file_text.replace(f"{OWNERSHIP_MARKER}\n", "", 1)


def _role_background_declared(role_body: str) -> bool:
    frontmatter, _ = split_frontmatter("role", role_body)
    return any(line.strip() == "background: true" for line in frontmatter.splitlines())


def expected_projections(
    repo: Path,
    *,
    presets: dict[str, Preset] | None = None,
    catalog: ModelCatalog | None = None,
) -> dict[Path, str]:
    """roles＋presets＋catalog → 期望生成樹（單一機械投影路徑）。"""
    policy = load_presets(repo) if presets is None else presets
    cat = load_catalog(repo) if catalog is None else catalog
    roles = load_role_specs(repo)
    assert roles.keys() == policy.keys(), (
        f"roles/preset mismatch — roles-only: {sorted(set(roles) - set(policy))}, "
        f"preset-only: {sorted(set(policy) - set(roles))}"
    )
    resolved = resolve_deployment(cat, policy)
    expected: dict[Path, str] = {}
    for slug, preset in policy.items():
        declared = _role_background_declared(roles[slug])
        assert declared == preset.background, (
            f"preset {slug!r} background={preset.background} 但 roles frontmatter "
            f"{'有' if declared else '無'} background 宣告——deployment 與 authoring"
            " 需同步（parity gate）"
        )
        for harness in preset.harness:
            binding, effort = resolved[slug][harness]
            expected[repo / "agents" / harness / f"{slug}.md"] = render_registry(
                slug, roles[slug], harness, binding, effort
            )
    return expected


def inventory_owned_outputs(repo: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for target in ("zcode", "claude"):
        for path in sorted((repo / "agents" / target).glob("*.md")):
            file_text = path.read_text(encoding="utf-8")
            if is_owned(file_text):
                outputs[path] = file_text
    return outputs


def compare_projection(
    expected: dict[Path, str],
    owned: dict[Path, str],
) -> list[Path]:
    paths = set(expected) | set(owned)
    return sorted(path for path in paths if expected.get(path) != owned.get(path))


def validate_collisions(
    expected: dict[Path, str],
    *,
    adopt_legacy: bool,
    legacy_paths: set[str] | None = None,
) -> None:
    allowlist = LEGACY_REVIEWER_OUTPUTS if legacy_paths is None else legacy_paths
    collisions = [
        path
        for path in expected
        if path.exists()
        and not is_owned(path.read_text(encoding="utf-8"))
        and (
            not adopt_legacy
            or "/".join(path.parts[-3:]) not in allowlist
            or without_marker(expected[path]) != path.read_text(encoding="utf-8")
        )
    ]
    assert not collisions, f"unmarked same-name outputs block sync: {collisions}"


def atomic_write(path: Path, file_text: str) -> None:
    """temp file + os.replace——撕裂中斷不留半損檔（marker 半損會卡死後續 sync）。"""
    fd, tmp_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(file_text)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def apply_projection(
    expected: dict[Path, str],
    owned: dict[Path, str],
    *,
    adopt_legacy: bool = False,
    legacy_paths: set[str] | None = None,
) -> None:
    validate_collisions(expected, adopt_legacy=adopt_legacy, legacy_paths=legacy_paths)
    for path, file_text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if owned.get(path) != file_text:
            atomic_write(path, file_text)
    for stale in set(owned) - set(expected):
        stale.unlink()


def render_map(
    expected: dict[Path, str],
    *,
    presets: dict[str, Preset],
    owned: dict[Path, str] | None = None,
    resolved: dict[str, dict[str, tuple[DispatchBinding | None, str | None]]]
    | None = None,
    catalog: ModelCatalog | None = None,
    verbose: bool = False,
) -> str:
    """role/requirement/zcode/claude 四欄（registry 欄反映磁碟現況——owned 導出）。

    verbose 追加 preset／binding／model identity／token kind／capabilities 欄
    （--map --verbose 導航用；requirement 欄＝presets 的 legacy 相容 token）。
    """
    on_disk = (
        {(path.parent.name, path.stem) for path in owned}
        if owned is not None
        else {(path.parent.name, path.stem) for path in expected}
    )
    header = "role\trequirement\tzcode\tclaude"
    if verbose:
        assert resolved is not None and catalog is not None, (
            "render_map(verbose=True) 需 resolved 與 catalog（main --map --verbose 提供）"
        )
        header += (
            "\tpreset.zcode_binding\tpreset.zcode_model\tpreset.zcode_effort"
            "\tpreset.zcode_token_kind\tpreset.zcode_model_identity"
            "\tpreset.claude_binding\tpreset.claude_model\tpreset.claude_effort"
            "\tpreset.claude_token_kind\tpreset.claude_model_identity"
            "\tmodel_capabilities"
        )
    rows = [header]
    for role in sorted(presets):
        preset = presets[role]
        zcode = "yes" if ("zcode", role) in on_disk else "no"
        claude = "yes" if ("claude", role) in on_disk else "no"
        row = f"{role}\t{preset.requirement}\t{zcode}\t{claude}"
        if verbose:
            assert resolved is not None and catalog is not None, (
                "render_map(verbose=True) 需 resolved 與 catalog（main --map --verbose 提供）"
            )
            cells = [row]
            for member in ("zcode", "claude"):
                binding, effort = resolved[role][member]
                cells.extend(
                    (
                        binding.id if binding else "inherit",
                        binding.token if binding else "-",
                        effort if effort else "-",
                        binding.token_kind if binding else "-",
                        binding.model_identity if binding else "-",
                    )
                )
            caps = sorted(
                f"{mid}:{cap.name}"
                for mid in sorted(
                    {
                        b.model_identity
                        for b, _ in resolved[role].values()
                        if b is not None
                    }
                )
                for cap in catalog.identities[mid].capabilities
            )
            cells.append(",".join(caps) if caps else "-")
            row = "\t".join(cells)
        rows.append(row)
    return "\n".join(rows)


_MODES = {"check", "map", "sync", "adopt-legacy"}


def main(
    repo: Path,
    *,
    mode: str,
    legacy_paths: set[str] | None = None,
    verbose: bool = False,
) -> int:
    """exit 語義：0=綠、1=drift（生成物 vs 源，重跑 sync 可修）、2=fatal
    （presets／catalog 缺席或 schema 違規／roles-preset mismatch／binding
    不相容——修源重跑，sync 修不了）。"""
    assert mode in _MODES, f"unknown mode: {mode}（合法：{sorted(_MODES)}）"
    try:
        catalog = load_catalog(repo)
        presets = load_presets(repo)
    except FileNotFoundError as exc:
        print(f"fatal (source missing): {exc}", file=sys.stderr)
        return 2
    except AssertionError as exc:
        print(f"fatal (presets/catalog schema): {exc}", file=sys.stderr)
        return 2
    try:
        expected = expected_projections(repo, presets=presets, catalog=catalog)
    except AssertionError as exc:
        print(f"fatal (roles/preset mismatch): {exc}", file=sys.stderr)
        return 2
    owned = inventory_owned_outputs(repo)
    drift = compare_projection(expected, owned)
    if mode == "check":
        for path in drift:
            print(path)
        return 1 if drift else 0
    if mode == "map":
        resolved = resolve_deployment(catalog, presets)
        print(
            render_map(
                expected,
                presets=presets,
                owned=owned,
                resolved=resolved,
                catalog=catalog,
                verbose=verbose,
            )
        )
        return 0
    apply_projection(
        expected, owned, adopt_legacy=mode == "adopt-legacy", legacy_paths=legacy_paths
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check", action="store_true", help="唯讀比對，drift 列清單 exit 1"
    )
    group.add_argument("--map", action="store_true", help="印 role→registry 可用性表")
    group.add_argument(
        "--adopt-legacy", action="store_true", help="一次性收編 legacy unmarked 輸出"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="--map 擴充欄（preset/binding/model identity/token kind/capabilities）",
    )
    args = parser.parse_args()
    mode = (
        "check"
        if args.check
        else "map"
        if args.map
        else "adopt-legacy"
        if args.adopt_legacy
        else "sync"
    )
    raise SystemExit(
        main(Path(__file__).resolve().parents[1], mode=mode, verbose=args.verbose)
    )
